//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Domain
{
    using System;
    using System.Collections.Generic;
    
    public partial class Acerto
    {
        public int Id { get; set; }
    
        public virtual Usuario Usuario { get; set; }
        public virtual Cenario Cenario { get; set; }
        public virtual Solucao Solucao { get; set; }
    }
}
