//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Domain
{
    using System;
    using System.Collections.Generic;
    
    public partial class Cenario
    {
        public Cenario()
        {
            this.Acerto = new HashSet<Acerto>();
            this.Solucao = new HashSet<Solucao>();
            this.Imagem = new HashSet<Imagem>();
        }
    
        public int Id { get; set; }
        public string Nome { get; set; }
        public string DicaEscrita { get; set; }
        public string DicaFalada { get; set; }
    
        public virtual ICollection<Acerto> Acerto { get; set; }
        public virtual ICollection<Solucao> Solucao { get; set; }
        public virtual Fundo Fundo { get; set; }
        public virtual ICollection<Imagem> Imagem { get; set; }
    }
}
