//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Domain
{
    using System;
    using System.Collections.Generic;
    
    public partial class Figura
    {
        public Figura()
        {
            this.Objeto = new HashSet<Objeto>();
            this.Fundo = new HashSet<Fundo>();
            this.Imagem = new HashSet<Imagem>();
        }
    
        public int Id { get; set; }
        public string Path { get; set; }
    
        public virtual ICollection<Objeto> Objeto { get; set; }
        public virtual ICollection<Fundo> Fundo { get; set; }
        public virtual ICollection<Imagem> Imagem { get; set; }
    }
}
