//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Domain
{
    using System;
    using System.Collections.Generic;
    
    public partial class Imagem
    {
        public int Id { get; set; }
        public double Altura { get; set; }
        public double Largura { get; set; }
        public double PosX { get; set; }
        public double PosY { get; set; }
        public string Fala { get; set; }
        public string Som { get; set; }
        public short Momento { get; set; }
    
        public virtual Cenario Cenario { get; set; }
        public virtual Figura Figura { get; set; }
    }
}
