//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Domain
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class Model1Container : DbContext
    {
        public Model1Container()
            : base("name=Model1Container")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<Usuario> UsuarioSet { get; set; }
        public DbSet<Acerto> AcertoSet { get; set; }
        public DbSet<Solucao> SolucaoSet { get; set; }
        public DbSet<Cenario> CenarioSet { get; set; }
        public DbSet<Fundo> FundoSet { get; set; }
        public DbSet<Imagem> ImagemSet { get; set; }
        public DbSet<Formacao> FormacaoSet { get; set; }
        public DbSet<Silaba> SilabaSet { get; set; }
        public DbSet<Objeto> ObjetoSet { get; set; }
        public DbSet<Figura> FiguraSet { get; set; }
    }
}
