//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Domain
{
    using System;
    using System.Collections.Generic;
    
    public partial class Objeto
    {
        public Objeto()
        {
            this.Solucao = new HashSet<Solucao>();
        }
    
        public int Id { get; set; }
        public string Palavra { get; set; }
        public string Som { get; set; }
    
        public virtual ICollection<Solucao> Solucao { get; set; }
        public virtual Figura Figura { get; set; }
    }
}
