//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Domain
{
    using System;
    using System.Collections.Generic;
    
    public partial class Usuario
    {
        public Usuario()
        {
            this.Acerto = new HashSet<Acerto>();
        }
    
        public int Id { get; set; }
        public string Nome { get; set; }
        public short Idade { get; set; }
        public string Sexo { get; set; }
        public Nullable<short> Serie { get; set; }
        public string Senha { get; set; }
    
        public virtual ICollection<Acerto> Acerto { get; set; }
    }
}
